### ISSUE TITLE
Zepto - Mixed Active Content

### ISSUE THREAD

**Issue by RaymondLC92** [poppinss/youch#1]
Youch is using Zepto over HTTP rather than HTTPS this results in the script being blocked unless you disable  security.mixed_content.block_active_content in firefox.

Given that Zepto's domain doesn't utilize HTTPS and that the script seems to be quite ancient should the script be replaced?

**Comment by thetutlage** [comment]
The firefox should give error when your app is on `HTTPS` and Zepto is loaded via `HTTP`. Is that the case?

**Comment by RaymondLC92** [comment]
Yes, that is correct.

That is also the problem. Firefox gives you an error **and blocks zepto** requiring developers to unblock Mixed Active Content on all websites through about:config in order to view the responsible line.

**Comment by thetutlage** [comment]
Cool lemme fix it

**Comment by jpsc** [comment]
Maybe inlining Zepto also is a good way to improve the fact that if there is no connection it fails. 😇

**Comment by thetutlage** [comment]
Yes that is what I am going to do
