### ISSUE TITLE
Could not find a declaration file for this module

### ISSUE THREAD

**Issue by henry-ns** [poppinss/youch#25]
I try to use youch with typescript, but not find a declaration file (.d.ts). It would be nice to have this file or a @types package.

**Comment by lenivene** [comment]
I have same problem :)

**Comment by henry-ns** [comment]
@lenivene, if you want a temporary solution, create a .d.ts file and declare the module with what you use:

#### For example
Create a `youch.d.ts` file with:
```typescript
declare module 'youch' {
  import { Errback, Request } from 'express';

  class Youch {
    constructor(err: Errback, req: Request);

    toJSON(): Promise<any>;
  }
  export default Youch;
}
```
if you only use the constructor and `toJSON` function

**Comment by RomainLanz** [comment]
Hey! 👋 

Happy to accept a PR if someone want to add a definition file.

**Comment by henry-ns** [comment]
I can do, it will be a great learning experience.

**Comment by henry-ns** [comment]
better, @RomainLanz?

**Comment by avidcoder123** [comment]
I'm currently working on adding basic type script support to Youch. I'll submit a pull request when I'm done.
