### ISSUE TITLE
Getting "Missing stack frames"?

### ISSUE THREAD

**Issue by OmgImAlexis** [poppinss/youch#40]
Any idea what might be causing this? Using something similar to the demo but with ESM.

```js
import Youch from 'youch';
import { createServer } from 'http';

createServer((req, res) => {
	try {
		throw new Error('no username set!');
	} catch (error) {
		const youch = new Youch(error, req);

		youch
			.toHTML()
			.then(html => {
				res.writeHead(200, { 'content-type': 'text/html' });
				res.write(html);
				res.end();
			});
	}
}).listen(8000);
```

On page load I see this. Which I think is also another bug as the "show all frames" is selected but doesn't actually show anything. (After doing more research it seems to cache ticked or not in your browser on refresh but having it on doesn't actually do anything different).
![image](https://user-images.githubusercontent.com/6525926/148632281-5ce763a1-3bb1-4b2f-96bd-a42b7b10cac0.png)

Unticking it I see this.

![image](https://user-images.githubusercontent.com/6525926/148632285-10592f9b-c629-450b-8bfc-1b1ddb92be5d.png)

Ticking it again I see this.

![image](https://user-images.githubusercontent.com/6525926/148632293-014c75fa-baec-4c1b-8c05-f5a88222adcc.png)

**Comment by OmgImAlexis** [comment]
Found the issue, it doesn't support `file:` paths.

For example this file has these paths.

```
{ path: 'file:///home/xo/_/up-n-down/youch.js' }
{ path: 'node:events' }
{ path: 'node:_http_server' }
{ path: 'node:_http_common' }
```

**Comment by thetutlage** [comment]
Thanks for narrowing it down. I will look into it and add support for ESM as well
