### ISSUE TITLE
Feature request: dark mode support (system preference)

### ISSUE THREAD

**Issue by donaldp** [poppinss/youch#45]
### Description
Hey, thanks for the awesome package. I've been using `youch` as the default error reporting plugin for https://github.com/formidablejs for some time now and I'm really loving it.

Having said that, I would like to make a feature request. Support for dark mode (system preference) would be awesome. 

### Is this something you're interested in working on?
Yes

**Comment by thetutlage** [comment]
Added in v4 (Soon to be released). Yeah it look freaking 2.5 years 😅

**Comment by donaldp** [comment]
Fantastic!!! 🚀  Do you have an ETA for a stable release?

**Comment by thetutlage** [comment]
Waiting on certain community users to give beta a try and report back any issues they have faced.
