### ISSUE TITLE
Argument of method `toHTML` has an incorrect type

### ISSUE THREAD

**Issue by yorch** [poppinss/youch#50]
### Package version

3.3.2

### Describe the bug

TypeScript type for the argument of the method `toHTML` is incorrect, since the [implementation treats it as optional](https://github.com/poppinss/youch/compare/84f6eed516785d7b8252ac47e2e993d62885ec75...eec6e9ee0d80d59d87e3e8595283ba7347b26b4d#diff-79b8ec14b780ab50d4b8073d7d0f92496750e8438564b22f7dd58a91ffef9935R363-R365), but the [type as required](https://github.com/poppinss/youch/compare/eec6e9ee0d80d59d87e3e8595283ba7347b26b4d...61a1a0027576c17b8d21bcf47d9caab793aa1908#diff-7aa4473ede4abd9ec099e87fec67fd57afafaf39e05d493ab4533acc38547eb8R62).

**Comment by thetutlage** [comment]
Fixed by https://github.com/poppinss/youch/pull/51
