### ISSUE TITLE
Incorrect template exports

### ISSUE THREAD

**Issue by ahce** [poppinss/youch#58]
### Package version

4.1.0-beta.3

### Describe the bug

The template [exports](https://github.com/poppinss/youch/blob/v4.1.0-beta.3/package.json#L19) have the path  `"./build/templates/*/main.js"`, the correct value is `"./build/src/templates/*/main.js"`

**Comment by RomainLanz** [comment]
Hey @ahce! 👋🏻 

Can you make a PR for it?
